### ISSUE TITLE
iOS google play games setup

### ISSUE THREAD

**Issue by Dorokah** [playgameservices/ios-basic-samples#11]
I found the reason that cause this problem. For Android users who don't have a Google Game Play Service account, you will be guided to create one then you'll log in sucessfully. But there's no guide for IOS users to follow, it's the reason why cause the IOS users fail to sign in. Did anyone have the same problem? Or anybody have the solution to lead IOS users to create a game service account?

**Comment by xysverma** [comment]
I am having the same problem. Can someone let me know how to resolve it ?

**Comment by Dorokah** [comment]
Only Google can fix it with an update to the SDK. does anybody know how to contact them?

**Comment by GreenRollingHills** [comment]
I ensured that all test accounts are listed as testers as described [here](https://developers.google.com/games/services/console/testpub).  I tried the ButtonClicker demo app with google accounts that haven't created Google Game Play Service accounts and I couldn’t get it to work.

I then created a Google Game Play Service accounts for 2 of my test google accounts.  I used the NOX App Player located [here](https://www.bignox.com) to create the Google Game Play Service accounts.  I tried the buttonClicker demo app again without making any other changes.  I was able to successfully log in and set up a match between 2 iOS devices.

I am wondering...

Cocoa pods resulted in GoogleSignIn (2.4.0) being installed.  I am wondering if a later version will fix this issue.  The latest is 4.0.1. But as SotoiGhost [pointed out](https://github.com/playgameservices/ios-basic-samples/issues/14)  it is not compatible with Google Play Games Services.

**Comment by claywilkinson** [comment]
Google Play Game Services does not support creating the Gamer profile on iOS, which I believe is the source of your problem.  It is also why the dependency on GoogleSignIn is fixed at 2.4.0.  There is more information at: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html

**Comment by Dorokah** [comment]
It should be fixed

**Comment by ryanbourneuk** [comment]
I'm using the C++ sdk, and I'm unable to create a Google Play Games account on iOS. I am able to proceed through the sign-in screens but am then presented with the error code "internal error". My other account which is already set up with Google Play Games works perfectly fine.

Is this issue fixed or is account creation still not supported?

**Comment by claywilkinson** [comment]
At this time, account creation is not supported and as far as I know, there no plans to support it in the future.

**Comment by ryanbourneuk** [comment]
Ahhh okay, that does suck, especially after getting the SDK entirely integrated. There doesn't seem to be any mention of this within the documentation too. Is Google Play Games going to continue to be supported on iOS in the future or will it become Android only, considering that accounts cannot be created?

**Comment by chandruscm** [comment]
I am glad that I at least bumped into this post before I wasted more development time. This should have been mentioned in the documentation. After integrating the whole SDK with LibGDx + RoboVM, this is a nightmare :o

**Comment by ryanbourneuk** [comment]
@chandruscm Yep, although sadly I bumped into this afterwards. I'll still end up releasing for iOS as some may be able to use it, but I think for my next game I'll have to look at other solutions - how was the important detail of 'no account registrations' just left out?

**Comment by chandruscm** [comment]
@ryanbourneuk What are you developing on? Why not switch to Gamecenter? The RoboVM framework I am using has a GameKit support for Apple's Gamecenter. I rewrote the whole thing, now I've managed to get it working :) The whole point of having Google Play Game Services was to have a world-wide leaderboard across iOS and Android. Sadly that won't be happening :|

**Comment by ryanbourneuk** [comment]
I'm using cocos2d-x and sdkbox, and while it's tempting to switch back to Game Center I've decided not to as some players will still be able to use Google Play Games - if people have accounts from other devices they'll be able to log in. I believe on iOS I should be able to catch the errors from logging in and display a message if there is an issue. I suppose I could add in Game Center if they can't log in, but that'll be a decision for later on. Currently, I'm just looking at finishing off what I have, and I should be able to map most of the Google Play Games and Game Center APIs together with some sort of helper. That way, Game Center will just be a fallback for if Google Play Games is unreachable.
